
nombreCentro=CNM - Centro de Nivelacion
direccion=RECREO
telefono=0979084514

# Configuración de Base de Datos (Neon PostgreSQL)
db.url=jdbc:postgresql://ep-winter-sea-adexnh7y.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
db.user=neondb_owner
db.password=npg_XfVE2zWiqCM5

# Configuración de Correo (SMTP)
mail.username=tu_correo@gmail.com
mail.password=tu_contrasena_de_aplicacion